[#IOCIT-301] Replace oval with swagger-cli in lint-api
pagopa/io-functions-lollipop pull request #15
Opened 2023-02-20 16:19 UTC by fabriziopapi

#### List of Changes
see commit history

#### Motivation and Context

Oval do not support openapi 3.x specs: it will be replaced with swagger-cli validate.

#### How Has This Been Tested?

manual system test

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-02-20 17:47 UTC, gquadrati requested changes

2023-02-20 17:47 UTC, gquadrati commented on .devops/deploy-pipelines.yml
> +  #           openapiSpecPath: 'openapi/index.yaml'
We should either remove it or fix it..

2023-02-21 08:29 UTC, fabriziopapi commented on .devops/deploy-pipelines.yml
> +  #           openapiSpecPath: 'openapi/index.yaml'
fixed! 👍

2023-02-21 09:32 UTC, gquadrati approved these changes

2023-02-21 09:32 UTC, merged