[#IOCIT-344] Add revokePubKeys Queue handler
pagopa/io-functions-lollipop pull request #18
Opened 2023-02-21 18:30 UTC by AleDore

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-02-22 17:26 UTC, fabriziopapi commented on HandlePubKeyRevoke/handler.ts
> +                      Error("Cannot perform upsert CosmosDB")
```suggestion
                  TE.mapLeft(err =>
                    toTransientFailure(
                      Error(
                        `Cannot perform upsert CosmosDB: ${JSON.stringify(err)}`
                      )
```

2023-02-22 17:27 UTC, fabriziopapi commented on HandlePubKeyRevoke/handler.ts
> +          toTransientFailure(Error("Cannot perform find on CosmosDB"))()
```suggestion
        TE.mapLeft(err =>
          toTransientFailure(
            Error(`Cannot perform find on CosmosDB: ${JSON.stringify(err)}`)
          )()
```

2023-02-23 10:51 UTC, gquadrati requested changes

2023-02-23 10:51 UTC, gquadrati commented on HandlePubKeyRevoke/index.ts
> +  cosmosdbInstance.container("PIPPO")
Pippo? :D

2023-02-23 10:51 UTC, gquadrati commented on HandlePubKeyRevoke/handler.ts
> + *
Explain array order

2023-02-23 10:51 UTC, gquadrati commented on HandlePubKeyRevoke/handler.ts
> +                    )()
```suggestion
                    toTransientFailure(
                      Error("Cannot decode a VALID master lollipopPubKey")
                    )()
```

2023-02-23 10:51 UTC, gquadrati commented on HandlePubKeyRevoke/handler.ts
> +              ])
Switch to struct

2023-02-23 10:51 UTC, gquadrati commented on HandlePubKeyRevoke/handler.ts
> +                  RA.sequence(TE.ApplicativeSeq),
```suggestion
                  RA.sequence(TE.ApplicativePar),
```

2023-02-23 10:51 UTC, gquadrati commented on HandlePubKeyRevoke/handler.ts
> +    TE.map(constVoid),
```suggestion
```

2023-02-23 10:51 UTC, gquadrati commented on HandlePubKeyRevoke/__tests__/handler.test.ts
> +  it("GIVEN a valid revoke message that does not match master key WHEN master lollipopPubKey is retieved THEN it should upsert to REVOKED all pubKeys", async () => {
```suggestion
  it("GIVEN a valid revoke message that does not match master key WHEN master lollipopPubKey is retrieved THEN it should upsert to REVOKED all pubKeys", async () => {
```

2023-02-23 10:56 UTC, gquadrati commented on utils/lollipopKeys.ts
> +export const AssertionsRef = t.intersection([
rename to `AssertionRefByType`

2023-02-23 11:03 UTC, gquadrati commented on utils/errors.ts
> +      name: `cgn.exception.${logPrefix}.failure`
cgn?

2023-02-23 13:58 UTC, AleDore commented on HandlePubKeyRevoke/handler.ts
> + *
Modified

2023-02-23 15:46 UTC, merged